namespace WebApi.Core.Contracts.Enums
{
    public enum ErrorType
    {
        SIN_CAMBIOS,
        VALIDACION_PARAMETROS_ENTRADA,
        ERROR_INTERNO_EN_SERVIDOR,
        DATOS_DUPLICADOS,
        DATOS_NO_ENCONTRADOS,
        ERROR_INTERNO,
        PERSONA_NO_EXISTE,
        CONTRASEÑA_INCORRECTA,
        SIN_USUARIO,
        USUARIO_NO_ACTIVO,
        CUENTA_DUPLICADA,
        CLIENTE_NO_EXISTE,
        MOVIMIENTO_NO_EXISTE,
        CUENTA_NO_EXISTE,
        SALDO_EXCEDIDO,
        CUENTA_CON_MOVIMIENTOS,
        SIN_MOVIMIENTOS,
        TIENE_USUARIO,
        MOVIMIENTO_NO_MODIFICABLE
    }
}